DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    salary DOUBLE NOT NULL
);

INSERT INTO EMPLOYEES (name, salary) VALUES
('Chris', 10.00),
('Dante', 20.00);